### ISSUE TITLE
edit login

### ISSUE THREAD

**Issue by Giventicket** [knoteHOW/knotehow-api#10]
http://localhost:8000/api/users/login
=> reduce this api parameters to just "password"

**Comment by TheStarkor** [comment]
name 은 확실히 필요 없을 것 같은데 password 가 해시되어있는 상태라 email 정도는 받으면 좋을 것 같은데 어떤가요?

**Comment by Giventicket** [comment]
그럼 email은 수정 불가능하게 막아놓을께요! name만 제거해주세요 ㅎㅎ

**Comment by Giventicket** [comment]
아 근데 nickname 받을거면 그냥 login은 그대로 내비두고 front에서 nickname을 명시해주면 되겠네요!
