### ISSUE TITLE
get posts 개선 사항

### ISSUE THREAD

**Issue by Giventicket** [knoteHOW/knotehow-api#12]
api/post?school=SNU?dep=cs
위와 같이 특정학교, 특정학과의 카드 정보를 fetching해올 수 있도록 부탁합니다.
school=SNU, dep=all 이면 전체정보 쏴주시고
school=SNU, dep=main 이면 대표값 4개만 보내주세요!

**Comment by TheStarkor** [comment]
dept main 은 따로 구현하지 않을 것 같아요.

1. 어차피 화면 전환시에 추가 post 들을 받아와야 하는데 이게 요청 두개로 나뉘면 server cpu 처리량이 2배가 되는데
2. 그냥 front server memory 에 담아두기에 큰 용량도 아니라서 (어차피 전부 실 파일은 따로 있고 링크만 가져오는 형식이라) 한 번에 넘어갈 것 같아요.
3. 일단은 전체 넘겨주는 방식으로 갈 것 같고 이후에는 paging 해서 나눠 줄 것 같은데 그건 데이터 많아진 이후에 고려하면 될 것 같아요.

아 그리고 필터링이 가장 cost 가 높은 요청이라 어느정도는 front 쪽에서 처리를 하는 방향으로 가는게 좋은 것 같습니다. 현재 pdf 스트리밍까지 같이 돌릴 예정이라 잘 병렬화 해서 처리하는게 좋을 것 같아요 front 컴퓨팅 파워도 요즘 좋아서요.

**Comment by TheStarkor** [comment]
![image](https://user-images.githubusercontent.com/45455072/94439069-e451da80-01da-11eb-8e8c-4546877161d4.png)

이런 방식으로 요청하면 되고 따로 명시하지 않을 경우 전체 데이터 가져오니 all 입력 안해도 되는거 인지해주세요. (입력하면 filtering 실패합니다.) name=<작성자이름> 도 추가로 해두었으니 나중에 gitbook 참고해주세요
