### ISSUE TITLE
birth 변수 관련

### ISSUE THREAD

**Issue by Giventicket** [knoteHOW/knotehow-api#27]
![image](https://user-images.githubusercontent.com/39179946/97960728-5a0e1f00-1df5-11eb-8fa0-928bc8376c7c.png)
이미지 참조 해서 콘솔 창확인해보시면 2017-10-20 이런식으로 birthday 입력하게 될텐데 이렇게 back에서 데이터 입력방식 수정부탁드립니다.

**Comment by TheStarkor** [comment]
String 으로 바꿔두었습니다.
타입 제외 Data validation 은 전부 프론트에서 진행하면 될 것 같습니다.
