### ISSUE TITLE
사용자 정보 추가 요청

### ISSUE THREAD

**Issue by Giventicket** [knoteHOW/knotehow-api#5]
Sign up API request의 required 항목 다음과 같이 사용자 정보 추가 부탁드립니다.
required 항목 : 
1. 이름
2. 생년월일
3. 이메일
4. 대학교(런칭시작하는 초기의 학교들, "해당없음"으로 받을 예정)
5. 학과
6. 학년(1,2,3,4,"해당없음" 5개의 항목으로 받을 예정)
7. 비밀번호 -> 카카오 고유식별번호로 넘겨줄 예정

**Comment by TheStarkor** [comment]
생년월일 양식이 어떻게될까요?
