### ISSUE TITLE
데이터 전체 삭제 api 요청

### ISSUE THREAD

**Issue by Giventicket** [knoteHOW/knotehow-api#7]
저의 카톡 아이디가 예전에 실험적으로 가입해둔 아이디랑 똑같은데
무엇으로 가입했는지 잊어버려서 db에 있는 모든 데이터 전부 삭제해주는 api 하나만 만들어주시면 좋겠습니다.
코드에 직접 기입할 것은 아니라서 포스트맨으로 request 보내는 방식으로 간편하게 작동할 수 있도록 부탁드려요!

**Comment by TheStarkor** [comment]
이건 db 측면에서 너무 위험한 거 같아서 그냥 id 알려주면 수작업으로 삭제하는 방식이 좋을 것 같아요.
